### ISSUE TITLE
音频资源维护人员有误

### ISSUE THREAD

**Issue by oldking139** [karumo10/asoul-101#2]
https://github.com/karumo10/asoul-101/blob/99842a402d889c6637b594f69cfa80562dae3592/README.md?plain=1#L34
其中，奶粉罐仅提供了音频的托管。先在所有的音频整理/切片都是由 _[A-soul Studio 内容组](https://space.bilibili.com/674044855)_ 产出的。

**Comment by karumo10** [comment]
67c953a5bbcaa440727f18ac338ef6990dfcec24 已更正
果咩那塞！！
